apiVersion: v1
kind: ServiceAccount
metadata:
  name: validator
  namespace: test-jwts
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: validate-sa-tokens
subjects:
- kind: ServiceAccount
  name: validator
  namespace: test-jwts
roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io
