apiVersion: v1
kind: Pod
metadata:
  name: validator
  namespace: test-jwts
spec:
  containers:
  - name: debian
    image: debian
    command:
      - sleep
      - "36000"
  automountServiceAccountToken: true
  serviceAccountName: validator
